services:
  bot:
    build: .
    command: bash start_bot.sh
    volumes:
      - ./:/code/
    networks:
      - test_task-network

    container_name: python_test_task2
    restart: always

networks:
  test_task-network:
