"""Add subscription_to_notifications table

Revision ID: 7325f3fa2494
Revises: ec2796b7e9a4
Create Date: 2024-03-13 16:54:03.472996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7325f3fa2494'
down_revision: Union[str, None] = 'ec2796b7e9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_to_notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_code', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_to_notifications')
    # ### end Alembic commands ###
